# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jLearn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jLearn
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTLinkingIOS',
]

  target 'jLearn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end


  target 'jLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jLearn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jLearn-tvOS

  # target 'jLearn-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

