# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jLearn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jLearn
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'jLearnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'jLearn-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jLearn-tvOS

  target 'jLearn-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
