export const GET_LEVEL_ACTION_REQUEST = "GET_LEVEL_ACTION_REQUEST";
export const GET_LEVEL_ACTION_SUCCESS = "GET_LEVEL_ACTION_SUCCESS";
export const GET_LEVEL_ACTION_FAILURE = "GET_LEVEL_ACTION_FAILURE";