export const REGISTER = "REGISTER";
export const LOGIN_ACTION_REQUEST = "LOGIN_ACTION_REQUEST";
export const LOGIN_ACTION_SUCCESS = "LOGIN_ACTION_SUCCESS";
export const LOGIN_ACTION_FAILURE = "LOGIN_ACTION_FAILURE";
export const SIGN_OUT_ACTION_REQUEST = "SIGN_OUT_ACTION_REQUEST";
export const SIGN_OUT_ACTION_SUCCESS = "SIGN_OUT_ACTION_SUCCESS";
export const SIGN_OUT_ACTION_FAILURE = "SIGN_OUT_ACTION_FAILURE";