export const GET_GRAMMARS_ACTION_REQUEST = "GET_GRAMMARS_ACTION_REQUEST";
export const GET_GRAMMARS_ACTION_SUCCESS = "GET_GRAMMARS_ACTION_SUCCESS";
export const GET_GRAMMARS_ACTION_FAILURE = "GET_GRAMMARS_ACTION_FAILURE";
export const RESET_GRAMMARS_ACTION_REQUEST = "RESET_GRAMMARS_ACTION_REQUEST";
export const RESET_GRAMMARS_ACTION_SUCCESS = "RESET_GRAMMARS_ACTION_SUCCESS";
export const RESET_GRAMMARS_ACTION_FAILURE = "RESET_GRAMMARS_ACTION_FAILURE";